// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUaa_d144vpqK7udTw0HYH65NMxfnUJ4',
    appId: '1:777782219652:web:97bb6ea80aee5991bec3d1',
    messagingSenderId: '777782219652',
    projectId: 'fullphysio-feldrise',
    authDomain: 'fullphysio-feldrise.firebaseapp.com',
    storageBucket: 'fullphysio-feldrise.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-1IMGODMf58RLm478a2D4zz7Npnl4reE',
    appId: '1:777782219652:android:b30a94ac8793dc19bec3d1',
    messagingSenderId: '777782219652',
    projectId: 'fullphysio-feldrise',
    storageBucket: 'fullphysio-feldrise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xYuxxu-5v9q-byWkHRFSptmzeoxGprY',
    appId: '1:777782219652:ios:ee1efbc701251000bec3d1',
    messagingSenderId: '777782219652',
    projectId: 'fullphysio-feldrise',
    storageBucket: 'fullphysio-feldrise.firebasestorage.app',
    iosBundleId: 'com.example.fullphysio',
  );
}
